<?php
/**
 * Implements hook_ctools_plugin_directory().
 */
function og_non_member_post_ctools_plugin_directory($module, $plugin) {
  if ($module == 'entityreference') {
    return "plugins/entityreference/$plugin";
  }
}


// ========================
dpm("OG NON MEMBER POST");

function og_non_member_post_node_load($nodes, $types) {
  dpm("OG NON MEMBER POST HOOK LOAD");
  dpm($nodes);
  dpm($types);
}
